/*
 * Stoatworks Labs - About window data for Repousse.
 *
 * Normally GENERATED by stoatworks-backend/scripts/sync-about.py from the
 * website's projects.json. This copy is HAND-WRITTEN in the generated shape,
 * because there is no website entry yet (2026-09-24). `guide` and `page` are
 * empty on purpose: the About block leaves a missing link out rather than
 * showing a button that opens a 404. The first real sync overwrites this file.
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Repousse";
    inline constexpr auto slug = "repousse";
    inline constexpr auto hook = "The picture hammered into a metal sheet and lit by a swinging lamp, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/repousse";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
